
delete from clase_objeto;
delete from rasgo_objeto;
delete from objeto;

delete from histograma_clase;
delete from histograma;
delete from rasgo_clase;
delete from rasgo;
delete from clase;
delete from tolerancia_rubro;
delete from grado;
delete from rubro_calidad;
delete from configuracion;

--CONFIGURACION
INSERT INTO CONFIGURACION(ID_SISTEMA, FONDO_H_MIN, FONDO_H_MAX, FONDO_S_MIN, FONDO_S_MAX, FONDO_V_MIN, FONDO_V_MAX)
VALUES('MAIZ', 80.0, 340.0, 6.0, NULL, 40.0, NULL);

--RUBROS CALIDAD
INSERT INTO RUBRO_CALIDAD(UID, NOMBRE, DESCRIPCION, ID_SISTEMA, CLASE_EVALUADOR_DESCUENTO, CLASE_EVALUADOR_VALOR_RUBRO)
VALUES (1,'MAIZ','Maiz','MAIZ', null, null);
INSERT INTO RUBRO_CALIDAD(UID, NOMBRE, DESCRIPCION, ID_SISTEMA, CLASE_EVALUADOR_DESCUENTO, CLASE_EVALUADOR_VALOR_RUBRO)
VALUES (2,'GRANO_PARTIDO','Grano Partido','MAIZ', 'procesamiento.descuento.AplicarDescuentoPorcentual', 'procesamiento.descuento.EvaluadorRubroPorcentaje');
INSERT INTO RUBRO_CALIDAD(UID, NOMBRE, DESCRIPCION, ID_SISTEMA, CLASE_EVALUADOR_DESCUENTO, CLASE_EVALUADOR_VALOR_RUBRO)
VALUES (3,'GRANO_DANIADO','Grano Dañado','MAIZ', 'procesamiento.descuento.AplicarDescuentoPorcentual', 'procesamiento.descuento.EvaluadorRubroPorcentaje');
INSERT INTO RUBRO_CALIDAD(UID, NOMBRE, DESCRIPCION, ID_SISTEMA, CLASE_EVALUADOR_DESCUENTO, CLASE_EVALUADOR_VALOR_RUBRO)
VALUES (4,'MATERIA_EXTRANIA','Materia Extraña','MAIZ', 'procesamiento.descuento.AplicarDescuentoPorcentual', 'procesamiento.descuento.EvaluadorRubroPorcentaje');
INSERT INTO RUBRO_CALIDAD(UID, NOMBRE, DESCRIPCION, ID_SISTEMA, CLASE_EVALUADOR_DESCUENTO, CLASE_EVALUADOR_VALOR_RUBRO)
VALUES (5,'CHAMICO','Semilla de Chamico','MAIZ', 'procesamiento.descuento.AplicarDescuentoDirecto', 'procesamiento.descuento.EvaluadorRubroCantidad');
INSERT INTO RUBRO_CALIDAD(UID, NOMBRE, DESCRIPCION, ID_SISTEMA, CLASE_EVALUADOR_DESCUENTO, CLASE_EVALUADOR_VALOR_RUBRO)
VALUES (6,'PESO_HECTOLITRICO','Peso Hectolítrico','MAIZ', 'procesamiento.descuento.AplicarDescuentoPorcentual', 'procesamiento.descuento.EvaluadorRubroPorcentaje');
INSERT INTO RUBRO_CALIDAD(UID, NOMBRE, DESCRIPCION, ID_SISTEMA, CLASE_EVALUADOR_DESCUENTO, CLASE_EVALUADOR_VALOR_RUBRO)
VALUES (7,'HUMEDAD','Humedad','MAIZ', 'procesamiento.descuento.AplicarDescuentoDirecto', 'procesamiento.descuento.EvaluadorRubroPorcentaje');
INSERT INTO RUBRO_CALIDAD(UID, NOMBRE, DESCRIPCION, ID_SISTEMA, CLASE_EVALUADOR_DESCUENTO, CLASE_EVALUADOR_VALOR_RUBRO)
VALUES (8,'GRANO_PICADO','Granos Picados','MAIZ', 'procesamiento.descuento.AplicarDescuentoPorcentual', 'procesamiento.descuento.EvaluadorRubroPorcentaje');
INSERT INTO RUBRO_CALIDAD(UID, NOMBRE, DESCRIPCION, ID_SISTEMA, CLASE_EVALUADOR_DESCUENTO, CLASE_EVALUADOR_VALOR_RUBRO)
VALUES (9,'TIPO','Tipo','MAIZ', 'procesamiento.descuento.AplicarDescuentoPorcentual', 'procesamiento.descuento.EvaluadorRubroPorcentaje');
INSERT INTO RUBRO_CALIDAD(UID, NOMBRE, DESCRIPCION, ID_SISTEMA, CLASE_EVALUADOR_DESCUENTO, CLASE_EVALUADOR_VALOR_RUBRO)
VALUES (10,'COLOR','Color','MAIZ', 'procesamiento.descuento.AplicarDescuentoPorcentual', 'procesamiento.descuento.EvaluadorRubroPorcentaje');

--GRADO
INSERT INTO GRADO(UID, NOMBRE, REBAJA, ES_FUERA_ESTANDAR, ID_SISTEMA) 
VALUES (1, 'Grado 1', 101, false, 'MAIZ');
INSERT INTO GRADO(UID, NOMBRE, REBAJA, ES_FUERA_ESTANDAR, ID_SISTEMA) 
VALUES (2, 'Grado 2', 100, false, 'MAIZ');
INSERT INTO GRADO(UID, NOMBRE, REBAJA, ES_FUERA_ESTANDAR, ID_SISTEMA) 
VALUES (3, 'Grado 3', 98.5, false, 'MAIZ');
INSERT INTO GRADO(UID, NOMBRE, REBAJA, ES_FUERA_ESTANDAR, ID_SISTEMA) 
VALUES (4, 'Fuera Estándar', 98.5, true, 'MAIZ');

--TOLERANCIA RUBRO
--GRADO 1
INSERT INTO TOLERANCIA_RUBRO(ID_GRADO, ID_RUBRO, VALOR, DESCUENTO)
VALUES (1, 7, 14.5, null);--HUMEDAD
INSERT INTO TOLERANCIA_RUBRO(ID_GRADO, ID_RUBRO, VALOR, DESCUENTO)
VALUES (1, 6, -75, null);--PESO HECTOLITRICO
INSERT INTO TOLERANCIA_RUBRO(ID_GRADO, ID_RUBRO, VALOR, DESCUENTO)
VALUES (1, 3, 3, null);--GRANO DAÑADO
INSERT INTO TOLERANCIA_RUBRO(ID_GRADO, ID_RUBRO, VALOR, DESCUENTO)
VALUES (1, 2, 2, null);--GRANO PARTIDO
INSERT INTO TOLERANCIA_RUBRO(ID_GRADO, ID_RUBRO, VALOR, DESCUENTO)
VALUES (1, 4, 1, null);--MATERIA EXTRAÑA
INSERT INTO TOLERANCIA_RUBRO(ID_GRADO, ID_RUBRO, VALOR, DESCUENTO)
VALUES (1, 5, 1, null);--CHAMICO

--GRADO 2
INSERT INTO TOLERANCIA_RUBRO(ID_GRADO, ID_RUBRO, VALOR, DESCUENTO)
VALUES (2, 7, 14.5, null);--HUMEDAD
INSERT INTO TOLERANCIA_RUBRO(ID_GRADO, ID_RUBRO, VALOR, DESCUENTO)
VALUES (2, 6, -72, null);--PESO HECTOLITRICO
INSERT INTO TOLERANCIA_RUBRO(ID_GRADO, ID_RUBRO, VALOR, DESCUENTO)
VALUES (2, 3, 5, null);--GRANO DAÑADO
INSERT INTO TOLERANCIA_RUBRO(ID_GRADO, ID_RUBRO, VALOR, DESCUENTO)
VALUES (2, 2, 3, null);--GRANO PARTIDO
INSERT INTO TOLERANCIA_RUBRO(ID_GRADO, ID_RUBRO, VALOR, DESCUENTO)
VALUES (2, 4, 1.5, null);--MATERIA EXTRAÑA
INSERT INTO TOLERANCIA_RUBRO(ID_GRADO, ID_RUBRO, VALOR, DESCUENTO)
VALUES (2, 5, 1, null);--CHAMICO

--GRADO 3
INSERT INTO TOLERANCIA_RUBRO(ID_GRADO, ID_RUBRO, VALOR, DESCUENTO)
VALUES (3, 7, 14.5, null);--HUMEDAD
INSERT INTO TOLERANCIA_RUBRO(ID_GRADO, ID_RUBRO, VALOR, DESCUENTO)
VALUES (3, 6, -69, null);--PESO HECTOLITRICO
INSERT INTO TOLERANCIA_RUBRO(ID_GRADO, ID_RUBRO, VALOR, DESCUENTO)
VALUES (3, 3, 8, null);--GRANO DAÑADO
INSERT INTO TOLERANCIA_RUBRO(ID_GRADO, ID_RUBRO, VALOR, DESCUENTO)
VALUES (3, 2, 5, null);--GRANO PARTIDO
INSERT INTO TOLERANCIA_RUBRO(ID_GRADO, ID_RUBRO, VALOR, DESCUENTO)
VALUES (3, 4, 2, null);--MATERIA EXTRAÑA
INSERT INTO TOLERANCIA_RUBRO(ID_GRADO, ID_RUBRO, VALOR, DESCUENTO)
VALUES (3, 5, 1, null);--CHAMICO

--FUERA DE ESTANDAR
INSERT INTO TOLERANCIA_RUBRO(ID_GRADO, ID_RUBRO, VALOR, DESCUENTO)
VALUES (4, 7, 14.5, 1);--HUMEDAD
INSERT INTO TOLERANCIA_RUBRO(ID_GRADO, ID_RUBRO, VALOR, DESCUENTO)
VALUES (4, 6, -69, 0.4);--PESO HECTOLITRICO
INSERT INTO TOLERANCIA_RUBRO(ID_GRADO, ID_RUBRO, VALOR, DESCUENTO)
VALUES (4, 3, 8, 1);--GRANO DAÑADO
INSERT INTO TOLERANCIA_RUBRO(ID_GRADO, ID_RUBRO, VALOR, DESCUENTO)
VALUES (4, 2, 5, 0.25);--GRANO PARTIDO
INSERT INTO TOLERANCIA_RUBRO(ID_GRADO, ID_RUBRO, VALOR, DESCUENTO)
VALUES (4, 4, 2, 1);--MATERIA EXTRAÑA
INSERT INTO TOLERANCIA_RUBRO(ID_GRADO, ID_RUBRO, VALOR, DESCUENTO)
VALUES (4, 5, 1, 1.3);--CHAMICO


--CLASES
INSERT INTO CLASE(UID, NOMBRE, DESCRIPCION, COLOR_RGB, ORDEN_EVALUACION, ID_RUBRO, INDETERMINADO, OBJETO_REFERENCIA)
  VALUES(1, 'MAIZ_AMARILLO', 'Maiz Amarillo ', -13369549, 5, 1, false, false);
INSERT INTO CLASE(UID, NOMBRE, DESCRIPCION, COLOR_RGB, ORDEN_EVALUACION, ID_RUBRO, INDETERMINADO, OBJETO_REFERENCIA)
  VALUES(2, 'INDETERMINADO', 'Indeterminado', -65536, -1, 4, true, false);
INSERT INTO CLASE(UID, NOMBRE, DESCRIPCION, COLOR_RGB, ORDEN_EVALUACION, ID_RUBRO, INDETERMINADO, OBJETO_REFERENCIA)
  VALUES(3, 'GRANO_PARTIDO', 'Grano Partido', -16750900, 3, 2, false, false);
INSERT INTO CLASE(UID, NOMBRE, DESCRIPCION, COLOR_RGB, ORDEN_EVALUACION, ID_RUBRO, INDETERMINADO, OBJETO_REFERENCIA)
  VALUES(4, 'GRANO_DANIADO', 'Grano Dañado', -26368, 4, 3, false, false);
INSERT INTO CLASE(UID, NOMBRE, DESCRIPCION, COLOR_RGB, ORDEN_EVALUACION, ID_RUBRO, INDETERMINADO, OBJETO_REFERENCIA)
  VALUES(5, 'MATERIA_EXTRANIA', 'Materia Extraña', -256, 2, 4, false, false);
INSERT INTO CLASE(UID, NOMBRE, DESCRIPCION, COLOR_RGB, ORDEN_EVALUACION, ID_RUBRO, INDETERMINADO, OBJETO_REFERENCIA)
  VALUES(6, 'OBJETO_REFERENCIA', 'Objeto de referencia', -39373, -1, null, false, true);
INSERT INTO CLASE(UID, NOMBRE, DESCRIPCION, COLOR_RGB, ORDEN_EVALUACION, ID_RUBRO, INDETERMINADO, OBJETO_REFERENCIA)
  VALUES(7, 'CHAMICO', 'Chamico', -16751002, 1, 5, false, false);
  
INSERT INTO CLASE(UID, NOMBRE, DESCRIPCION, COLOR_RGB, ORDEN_EVALUACION, ID_RUBRO, INDETERMINADO, OBJETO_REFERENCIA)
  VALUES(8, 'MAIZ_COLORADO', 'Maiz Colorado', -13369549, 6, 1, false, false);
INSERT INTO CLASE(UID, NOMBRE, DESCRIPCION, COLOR_RGB, ORDEN_EVALUACION, ID_RUBRO, INDETERMINADO, OBJETO_REFERENCIA)
  VALUES(9, 'MAIZ_BLANCO', 'Maiz Blanco', -13369549, 5, 1, false, false);
  

  --INSERT INTO CLASE(UID, NOMBRE, DESCRIPCION, COLOR_RGB, ORDEN_EVALUACION, AGRUPADOR)
--  VALUES(5, 'GRANO_PICADO', 'Grano Picado', -256, 3, 'Grano Picado');
--RASGOS
  INSERT INTO RASGO(UID, NOMBRE, DESCRIPCION, NOMBRE_EVALUADOR_RASGO, VISIBLE)
  VALUES(1, 'AREA', 'Area del objeto', 'procesamiento.clasificacion.Area','true');
INSERT INTO RASGO(UID, NOMBRE, DESCRIPCION, NOMBRE_EVALUADOR_RASGO, VISIBLE)
  VALUES(2, 'ASPECT RADIO', 'Aspect Radio', 'procesamiento.clasificacion.AspectRatio','true');
INSERT INTO RASGO(UID, NOMBRE, DESCRIPCION, NOMBRE_EVALUADOR_RASGO, VISIBLE)
  VALUES(3, 'CIRCULARIDAD', 'Circularidad', 'procesamiento.clasificacion.Circularidad','true');
INSERT INTO RASGO(UID, NOMBRE, DESCRIPCION, NOMBRE_EVALUADOR_RASGO, VISIBLE)
  VALUES(4, 'CURVATURA', 'Curvatura', 'procesamiento.clasificacion.Curvatura','false');
INSERT INTO RASGO(UID, NOMBRE, DESCRIPCION, NOMBRE_EVALUADOR_RASGO, VISIBLE)
  VALUES(5, 'DIAMETRO', 'Diametro', 'procesamiento.clasificacion.Diametro','true');
INSERT INTO RASGO(UID, NOMBRE, DESCRIPCION, NOMBRE_EVALUADOR_RASGO, VISIBLE)
  VALUES(6, 'SUMA_ANGULOS', 'Sumatoria Angulos', 'procesamiento.clasificacion.SumaAngulos','false');
INSERT INTO RASGO(UID, NOMBRE, DESCRIPCION, NOMBRE_EVALUADOR_RASGO, VISIBLE)
  VALUES(7, 'HISTOGRAMA_RGB', 'Histogramas', 'procesamiento.clasificacion.EvaluadorHistogramaRGB','false');
INSERT INTO RASGO(UID, NOMBRE, DESCRIPCION, NOMBRE_EVALUADOR_RASGO, VISIBLE)
  VALUES(8, 'HISTOGRAMA_GRIS', 'Histogramas', 'procesamiento.clasificacion.EvaluadorHistogramaGris','false');
INSERT INTO RASGO(UID, NOMBRE, DESCRIPCION, NOMBRE_EVALUADOR_RASGO, VISIBLE)
  VALUES(9, 'HISTOGRAMA_H', 'Histogramas', 'procesamiento.clasificacion.EvaluadorHistogramaH','true');
INSERT INTO RASGO(UID, NOMBRE, DESCRIPCION, NOMBRE_EVALUADOR_RASGO, VISIBLE)
  VALUES(10, 'HISTOGRAMA_S', 'Histogramas', 'procesamiento.clasificacion.EvaluadorHistogramaS','false');
INSERT INTO RASGO(UID, NOMBRE, DESCRIPCION, NOMBRE_EVALUADOR_RASGO, VISIBLE)
  VALUES(11, 'HISTOGRAMA_V', 'Histogramas', 'procesamiento.clasificacion.EvaluadorHistogramaV','false');
INSERT INTO RASGO(UID, NOMBRE, DESCRIPCION, NOMBRE_EVALUADOR_RASGO, VISIBLE)
  VALUES(12, 'HISTOGRAMA_HSV', 'Histogramas', 'procesamiento.clasificacion.EvaluadorHistogramaHSV','true');

INSERT INTO RASGO(UID, NOMBRE, DESCRIPCION, NOMBRE_EVALUADOR_RASGO, VISIBLE)
VALUES(13, 'PUNTOS_DIVISION', 'Puntos de división', 'procesamiento.clasificacion.CantidadPuntosDivision','false');

--RASGO_CLASE
--MAIZ
  INSERT INTO RASGO_CLASE(ID_CLASE, ID_RASGO, MINIMO, MAXIMO, SUM_VALOR, SUM_VALOR_CUADRADO, CANT_VALORES, PESO, CALCULAR_VALOR_MEDIO, DETERMINANTE,RANGO_VARIABLE, INDICE)
  VALUES(1, 1, NULL, NULL, NULL, NULL, NULL, '1.0', 'false', 'false', 'true', 1);
  INSERT INTO RASGO_CLASE(ID_CLASE, ID_RASGO, MINIMO, MAXIMO, SUM_VALOR, SUM_VALOR_CUADRADO, CANT_VALORES, PESO, CALCULAR_VALOR_MEDIO, DETERMINANTE,RANGO_VARIABLE, INDICE)
  VALUES(1, 2, 0.4, 1.0, NULL, NULL, NULL, '1.0', 'false', 'true', 'true', 2);
  INSERT INTO RASGO_CLASE(ID_CLASE, ID_RASGO, MINIMO, MAXIMO, SUM_VALOR, SUM_VALOR_CUADRADO, CANT_VALORES, PESO, CALCULAR_VALOR_MEDIO, DETERMINANTE,RANGO_VARIABLE, INDICE)
  VALUES(1, 3, 0.7, 1.0, NULL, NULL, NULL, '1.0', 'false', 'true', 'true', 3);
  INSERT INTO RASGO_CLASE(ID_CLASE, ID_RASGO, MINIMO, MAXIMO, SUM_VALOR, SUM_VALOR_CUADRADO, CANT_VALORES, PESO, CALCULAR_VALOR_MEDIO, DETERMINANTE,RANGO_VARIABLE, INDICE)
  VALUES(1, 5, '4.76', NULL, NULL, NULL, NULL, '1.0', 'false', 'true', 'false', 5);
  INSERT INTO RASGO_CLASE(ID_CLASE, ID_RASGO, MINIMO, MAXIMO, SUM_VALOR, SUM_VALOR_CUADRADO, CANT_VALORES, PESO, CALCULAR_VALOR_MEDIO, DETERMINANTE,RANGO_VARIABLE, INDICE)
  VALUES(1, 12, 0.75, 1.0, NULL, NULL, NULL, '10.0', 'false', 'true', 'false', 7);

  --MAIZ COLORADO
  INSERT INTO RASGO_CLASE(ID_CLASE, ID_RASGO, MINIMO, MAXIMO, SUM_VALOR, SUM_VALOR_CUADRADO, CANT_VALORES, PESO, CALCULAR_VALOR_MEDIO, DETERMINANTE,RANGO_VARIABLE, INDICE)
  VALUES(8, 1, NULL, NULL, NULL, NULL, NULL, '1.0', 'false', 'false', 'true', 1);
  INSERT INTO RASGO_CLASE(ID_CLASE, ID_RASGO, MINIMO, MAXIMO, SUM_VALOR, SUM_VALOR_CUADRADO, CANT_VALORES, PESO, CALCULAR_VALOR_MEDIO, DETERMINANTE,RANGO_VARIABLE, INDICE)
  VALUES(8, 2, 0.4, 1.0, NULL, NULL, NULL, '1.0', 'false', 'true', 'true', 2);
  INSERT INTO RASGO_CLASE(ID_CLASE, ID_RASGO, MINIMO, MAXIMO, SUM_VALOR, SUM_VALOR_CUADRADO, CANT_VALORES, PESO, CALCULAR_VALOR_MEDIO, DETERMINANTE,RANGO_VARIABLE, INDICE)
  VALUES(8, 3, 0.7, 1.0, NULL, NULL, NULL, '1.0', 'false', 'true', 'true', 3);
  INSERT INTO RASGO_CLASE(ID_CLASE, ID_RASGO, MINIMO, MAXIMO, SUM_VALOR, SUM_VALOR_CUADRADO, CANT_VALORES, PESO, CALCULAR_VALOR_MEDIO, DETERMINANTE,RANGO_VARIABLE, INDICE)
  VALUES(8, 5, '4.76', NULL, NULL, NULL, NULL, '1.0', 'false', 'true', 'false', 5);
  INSERT INTO RASGO_CLASE(ID_CLASE, ID_RASGO, MINIMO, MAXIMO, SUM_VALOR, SUM_VALOR_CUADRADO, CANT_VALORES, PESO, CALCULAR_VALOR_MEDIO, DETERMINANTE,RANGO_VARIABLE, INDICE)
  VALUES(8, 12, 0.80, 1.0, NULL, NULL, NULL, '10.0', 'false', 'true', 'false', 7);

--MAIZ BLANCO
  INSERT INTO RASGO_CLASE(ID_CLASE, ID_RASGO, MINIMO, MAXIMO, SUM_VALOR, SUM_VALOR_CUADRADO, CANT_VALORES, PESO, CALCULAR_VALOR_MEDIO, DETERMINANTE,RANGO_VARIABLE, INDICE)
  VALUES(9, 1, NULL, NULL, NULL, NULL, NULL, '1.0', 'false', 'false', 'true', 1);
  INSERT INTO RASGO_CLASE(ID_CLASE, ID_RASGO, MINIMO, MAXIMO, SUM_VALOR, SUM_VALOR_CUADRADO, CANT_VALORES, PESO, CALCULAR_VALOR_MEDIO, DETERMINANTE,RANGO_VARIABLE, INDICE)
  VALUES(9, 2, 0.4, 1.0, NULL, NULL, NULL, '1.0', 'false', 'true', 'true', 2);
  INSERT INTO RASGO_CLASE(ID_CLASE, ID_RASGO, MINIMO, MAXIMO, SUM_VALOR, SUM_VALOR_CUADRADO, CANT_VALORES, PESO, CALCULAR_VALOR_MEDIO, DETERMINANTE,RANGO_VARIABLE, INDICE)
  VALUES(9, 3, 0.7, 1.0, NULL, NULL, NULL, '1.0', 'false', 'true', 'true', 3);
  INSERT INTO RASGO_CLASE(ID_CLASE, ID_RASGO, MINIMO, MAXIMO, SUM_VALOR, SUM_VALOR_CUADRADO, CANT_VALORES, PESO, CALCULAR_VALOR_MEDIO, DETERMINANTE,RANGO_VARIABLE, INDICE)
  VALUES(9, 5, '4.76', NULL, NULL, NULL, NULL, '1.0', 'false', 'true', 'false', 5);
  INSERT INTO RASGO_CLASE(ID_CLASE, ID_RASGO, MINIMO, MAXIMO, SUM_VALOR, SUM_VALOR_CUADRADO, CANT_VALORES, PESO, CALCULAR_VALOR_MEDIO, DETERMINANTE,RANGO_VARIABLE, INDICE)
  VALUES(9, 12, 0.85, 1.0, NULL, NULL, NULL, '10.0', 'false', 'true', 'false', 7);

  
  --GRANO PARTIDO
  INSERT INTO RASGO_CLASE(ID_CLASE, ID_RASGO, MINIMO, MAXIMO, SUM_VALOR, SUM_VALOR_CUADRADO, CANT_VALORES, PESO, CALCULAR_VALOR_MEDIO, DETERMINANTE,RANGO_VARIABLE, INDICE)
  VALUES(3, 1, NULL, NULL, NULL, NULL, NULL, '1.0', 'false', 'false', 'true', 1);
  INSERT INTO RASGO_CLASE(ID_CLASE, ID_RASGO, MINIMO, MAXIMO, SUM_VALOR, SUM_VALOR_CUADRADO, CANT_VALORES, PESO, CALCULAR_VALOR_MEDIO, DETERMINANTE,RANGO_VARIABLE, INDICE)
  VALUES(3, 2, NULL, 1.0, NULL, NULL, NULL, '1.0', 'false', 'false', 'true', 2);
  INSERT INTO RASGO_CLASE(ID_CLASE, ID_RASGO, MINIMO, MAXIMO, SUM_VALOR, SUM_VALOR_CUADRADO, CANT_VALORES, PESO, CALCULAR_VALOR_MEDIO, DETERMINANTE,RANGO_VARIABLE, INDICE)
  VALUES(3, 3, NULL, 1.0, NULL, NULL, NULL, '1.0', 'false', 'false', 'true', 3);
  INSERT INTO RASGO_CLASE(ID_CLASE, ID_RASGO, MINIMO, MAXIMO, SUM_VALOR, SUM_VALOR_CUADRADO, CANT_VALORES, PESO, CALCULAR_VALOR_MEDIO, DETERMINANTE,RANGO_VARIABLE, INDICE)
  VALUES(3, 5, '0.0', '4.76', NULL, NULL, NULL, '1.0', 'false', 'true', 'false', 5);
  INSERT INTO RASGO_CLASE(ID_CLASE, ID_RASGO, MINIMO, MAXIMO, SUM_VALOR, SUM_VALOR_CUADRADO, CANT_VALORES, PESO, CALCULAR_VALOR_MEDIO, DETERMINANTE,RANGO_VARIABLE, INDICE)
  VALUES(3, 12, 0.5, 1.0, NULL, NULL, NULL, '10.0', 'false', 'true', 'false', 7);

  --GRANO DAÑADO
  INSERT INTO RASGO_CLASE(ID_CLASE, ID_RASGO, MINIMO, MAXIMO, SUM_VALOR, SUM_VALOR_CUADRADO, CANT_VALORES, PESO, CALCULAR_VALOR_MEDIO, DETERMINANTE,RANGO_VARIABLE, INDICE)
  VALUES(4, 1, NULL, NULL, NULL, NULL, NULL, '1.0', 'false', 'false', 'true', 1);
  INSERT INTO RASGO_CLASE(ID_CLASE, ID_RASGO, MINIMO, MAXIMO, SUM_VALOR, SUM_VALOR_CUADRADO, CANT_VALORES, PESO, CALCULAR_VALOR_MEDIO, DETERMINANTE,RANGO_VARIABLE, INDICE)
  VALUES(4, 2, 0.4, 1.0, NULL, NULL, NULL, '1.0', 'false', 'true', 'true', 2);
  INSERT INTO RASGO_CLASE(ID_CLASE, ID_RASGO, MINIMO, MAXIMO, SUM_VALOR, SUM_VALOR_CUADRADO, CANT_VALORES, PESO, CALCULAR_VALOR_MEDIO, DETERMINANTE,RANGO_VARIABLE, INDICE)
  VALUES(4, 3, 0.7, 1.0, NULL, NULL, NULL, '1.0', 'false', 'true', 'true', 3);
  INSERT INTO RASGO_CLASE(ID_CLASE, ID_RASGO, MINIMO, MAXIMO, SUM_VALOR, SUM_VALOR_CUADRADO, CANT_VALORES, PESO, CALCULAR_VALOR_MEDIO, DETERMINANTE,RANGO_VARIABLE, INDICE)
  VALUES(4, 5, 4.76, NULL, NULL, NULL, NULL, '1.0', 'false', 'true', 'true', 5);
  INSERT INTO RASGO_CLASE(ID_CLASE, ID_RASGO, MINIMO, MAXIMO, SUM_VALOR, SUM_VALOR_CUADRADO, CANT_VALORES, PESO, CALCULAR_VALOR_MEDIO, DETERMINANTE,RANGO_VARIABLE, INDICE)
  VALUES(4, 12, 0.89, 1.0, NULL, NULL, NULL, '10.0', 'false', 'true', 'false', 7);

  --MATERIA EXTRAÑA
  INSERT INTO RASGO_CLASE(ID_CLASE, ID_RASGO, MINIMO, MAXIMO, SUM_VALOR, SUM_VALOR_CUADRADO, CANT_VALORES, PESO, CALCULAR_VALOR_MEDIO, DETERMINANTE,RANGO_VARIABLE, INDICE)
  VALUES(5, 1, NULL, NULL, NULL, NULL, NULL, '1.0', 'false', 'false', 'true', 1);
  INSERT INTO RASGO_CLASE(ID_CLASE, ID_RASGO, MINIMO, MAXIMO, SUM_VALOR, SUM_VALOR_CUADRADO, CANT_VALORES, PESO, CALCULAR_VALOR_MEDIO, DETERMINANTE,RANGO_VARIABLE, INDICE)
  VALUES(5, 2, NULL, 1.0, NULL, NULL, NULL, '1.0', 'false', 'false', 'true', 2);
  INSERT INTO RASGO_CLASE(ID_CLASE, ID_RASGO, MINIMO, MAXIMO, SUM_VALOR, SUM_VALOR_CUADRADO, CANT_VALORES, PESO, CALCULAR_VALOR_MEDIO, DETERMINANTE,RANGO_VARIABLE, INDICE)
  VALUES(5, 3, NULL, 1.0, NULL, NULL, NULL, '1.0', 'false', 'false', 'true', 3);
  INSERT INTO RASGO_CLASE(ID_CLASE, ID_RASGO, MINIMO, MAXIMO, SUM_VALOR, SUM_VALOR_CUADRADO, CANT_VALORES, PESO, CALCULAR_VALOR_MEDIO, DETERMINANTE,RANGO_VARIABLE, INDICE)
  VALUES(5, 5, NULL, NULL, NULL, NULL, NULL, '1.0', 'false', 'false', 'true', 5);


  --OBJETO DE REFERENCIA
  INSERT INTO RASGO_CLASE(ID_CLASE, ID_RASGO, MINIMO, MAXIMO, SUM_VALOR, SUM_VALOR_CUADRADO, CANT_VALORES, PESO, CALCULAR_VALOR_MEDIO, DETERMINANTE,RANGO_VARIABLE, INDICE)
  VALUES(6, 1, NULL, NULL, NULL, NULL, NULL, '1.0', 'false', 'false', 'true', 1);
  INSERT INTO RASGO_CLASE(ID_CLASE, ID_RASGO, MINIMO, MAXIMO, SUM_VALOR, SUM_VALOR_CUADRADO, CANT_VALORES, PESO, CALCULAR_VALOR_MEDIO, DETERMINANTE,RANGO_VARIABLE, INDICE)
  VALUES(6, 2, 0.9, 1.0, NULL, NULL, NULL, '1.0', 'false', 'true', 'false', 2);
  INSERT INTO RASGO_CLASE(ID_CLASE, ID_RASGO, MINIMO, MAXIMO, SUM_VALOR, SUM_VALOR_CUADRADO, CANT_VALORES, PESO, CALCULAR_VALOR_MEDIO, DETERMINANTE,RANGO_VARIABLE, INDICE)
  VALUES(6, 3, 0.85, 1.0, NULL, NULL, NULL, '1.0', 'false', 'true', 'false', 3);
  INSERT INTO RASGO_CLASE(ID_CLASE, ID_RASGO, MINIMO, MAXIMO, SUM_VALOR, SUM_VALOR_CUADRADO, CANT_VALORES, PESO, CALCULAR_VALOR_MEDIO, DETERMINANTE,RANGO_VARIABLE, INDICE)
  VALUES(6, 5, NULL, NULL, NULL, NULL, NULL, '1.0', 'false', 'false', 'true', 5);

--CHAMICO
  INSERT INTO RASGO_CLASE(ID_CLASE, ID_RASGO, MINIMO, MAXIMO, SUM_VALOR, SUM_VALOR_CUADRADO, CANT_VALORES, PESO, CALCULAR_VALOR_MEDIO, DETERMINANTE,RANGO_VARIABLE, INDICE)
  VALUES(7, 1, NULL, NULL, NULL, NULL, NULL, '1.0', 'false', 'false', 'true', 1);
  INSERT INTO RASGO_CLASE(ID_CLASE, ID_RASGO, MINIMO, MAXIMO, SUM_VALOR, SUM_VALOR_CUADRADO, CANT_VALORES, PESO, CALCULAR_VALOR_MEDIO, DETERMINANTE,RANGO_VARIABLE, INDICE)
  VALUES(7, 2, 0.8, 1.0, NULL, NULL, NULL, '1.0', 'false', 'true', 'true', 2);
  INSERT INTO RASGO_CLASE(ID_CLASE, ID_RASGO, MINIMO, MAXIMO, SUM_VALOR, SUM_VALOR_CUADRADO, CANT_VALORES, PESO, CALCULAR_VALOR_MEDIO, DETERMINANTE,RANGO_VARIABLE, INDICE)
  VALUES(7, 3, 0.8, 1.0, NULL, NULL, NULL, '1.0', 'false', 'true', 'true', 3);
  INSERT INTO RASGO_CLASE(ID_CLASE, ID_RASGO, MINIMO, MAXIMO, SUM_VALOR, SUM_VALOR_CUADRADO, CANT_VALORES, PESO, CALCULAR_VALOR_MEDIO, DETERMINANTE,RANGO_VARIABLE, INDICE)
  VALUES(7, 5, '0.0', '5.0', NULL, NULL, NULL, '1.0', 'false', 'true', 'true', 5);
  INSERT INTO RASGO_CLASE(ID_CLASE, ID_RASGO, MINIMO, MAXIMO, SUM_VALOR, SUM_VALOR_CUADRADO, CANT_VALORES, PESO, CALCULAR_VALOR_MEDIO, DETERMINANTE,RANGO_VARIABLE, INDICE)
  VALUES(7, 12, 0.7, 1.0, NULL, NULL, NULL, '10.0', 'false', 'true', 'false', 7);
  
  commit;

